remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
downloads:
  zip_url: https://github.com/faraazb/annotator-web-extension/releases/latest/download/annotator-web-extension.zip
